Add rules around Rallying
seanKenkeremath/lords-and-lads pull request #15
Opened 2021-03-10 20:06 UTC by seanKenkeremath

2021-03-10 21:41 UTC, austenlux commented on README.md
> +If there is an active Uprising nail, a Lad may choose to call "Rally". If they do, their turn ends and they forfeit the ability to perform flips on that turn. By callling "Rally", that Lad has effect
says `callling` instead of `calling`

2021-03-10 21:46 UTC, austenlux commented on README.md
> +If there is an active Uprising nail, a Lad may choose to call "Rally". If they do, their turn ends and they forfeit the ability to perform flips on that turn. By callling "Rally", that Lad has effect
Also, maybe worth calling out that `r` in the equation is the number of Rallies? Just like it's specified that `f` is the number of flips. Probably obvious already, either way.

2021-03-10 21:47 UTC, austenlux requested changes
See comments

2021-03-10 22:07 UTC, seanKenkeremath commented on README.md
> +If there is an active Uprising nail, a Lad may choose to call "Rally". If they do, their turn ends and they forfeit the ability to perform flips on that turn. By callling "Rally", that Lad has effect
oh yeah i meant to do that. good call

2021-03-10 22:09 UTC, seanKenkeremath commented on README.md
> +If there is an active Uprising nail, a Lad may choose to call "Rally". If they do, their turn ends and they forfeit the ability to perform flips on that turn. By callling "Rally", that Lad has effect
@austenlux Fixed

2021-03-11 13:44 UTC, austenlux approved these changes

2021-03-11 16:58 UTC, merged